#RELACIONAMENTO ENTRE A TABELA ITENS DO PEDIDO E A TABELA PRODUTO:
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_PRODUTO
FOREIGN KEY(cod_prod)
REFERENCES tbl_produto (cod_prod);

#RELACIONAMENTO ENTRE A TABELA ITENS DO PEDIDO E A TABELA PEDIDO:
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_PEDIDO
FOREIGN KEY(cod_ped)
REFERENCES tbl_pedido (cod_ped);